version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    ignore:
      - dependency-name: "@quasar/app"
        versions: [">=2.4.3"]
