changelog:
  categories:
    - title: New Features 🚀
      labels:
        - "Feature"
    - title: Improvements 🦾
      labels:
        - "improvement"
        - "enhancement"
    - title: Bugfixes 🐛
      labels:
        - "bugfix"
        - "bug"
