changelog:
  categories:
    - title: New Features 🚀
      labels:
        - "Feature"
    - title: Improvements 🦾
      labels:
        - "improvement"
        - "Improvement"
        - "enhancement"
        - "Enhancement"
    - title: Bugfixes 🐛
      labels:
        - "bugfix"
        - "Bugfix"
        - "bug"
        - "Bug"
